package sales_purchase

import "time"

type SalesPurchase struct {
	Name                       string    `json:"name"`
	BuyerID                    string    `json:"buyer_id"`
	SellerID                   string    `json:"seller_id"`
	UserID                     string    `json:"user_id"`
	SellerBankID               string    `json:"seller_partner_id"`
	BuyerBankID                string    `json:"buyer_partner_id"`
	OrderID                    string    `json:"order_id"`
	DataID                     string    `json:"data_id"`
	OrderDate                  string    `json:"order_date"`
	PaymentType                string    `json:"payment_type"`
	TAX                        string    `json:"tax"`
	WebsiteAddress             string    `json:"website_address"`
	ContractID                 string    `json:"contract_id"`
	HSCode                     []string  `json:"hs_code"`
	ProductID                  []string  `json:"product_id"`
	Email                      string    `json:"email"`
	ShipName                   string    `json:"ship_name"`
	ShipAddress                []string  `json:"ship_address"`
	CompanyName                string    `json:"company_name"`
	SalesOrderCDN              string    `json:"sales_order_cdn"`
	BuyerOrderCDN              string    `json:"buyer_order_cdn"`
	SellerOrderNo              string    `json:"seller_order_no"`
	SellerOrderDate            string    `json:"seller_order_date"`
	BuyerOrderNo               string    `json:"buyer_order_no"`
	BuyerOrderDate             string    `json:"buyer_order_date"`
	ContractStatus             string    `json:"status"`
	OrderType                  string    `json:"order_type"`
	IncoTerms                  string    `json:"inco_terms"`
	State                      string    `json:"state"`
	City                       string    `json:"city"`
	Country                    string    `json:"country"`
	ApplicableRules            string    `json:"applicable_rules"`
	RuleType                   string    `json:"rule_type"`
	AvailableWithBy            string    `json:"available_withBy"`
	AvailableOption            string    `json:"available_option"`
	ProductName                []string  `json:"product_name"`
	ProductDescription         []string  `json:"description"`
	Quantity                   []int     `json:"quantity"`
	PrevQuantity               []int     `json:"prev_quantity"`
	Action                     string    `json:"action"`
	Price                      []string  `json:"price"`
	PreviousPrice              []string  `json:"prev_price"`
	Unit                       []string  `json:"unit"`
	InvoiceTax                 []string  `json:"invoice_tax"`
	InvoiceDiscount            []string  `json:"invoice_discount"`
	InvoiceOtherCharges        []string  `json:"invoice_othercharges"`
	BankAddress                []string  `json:"bank_address"`
	BankName                   string    `json:"bank_name"`
	ContractDate               string    `json:"contract_date"`
	OtherBankAccNo             string    `json:"otherbank_accNo"`
	SwiftCode                  string    `json:"swiftcode"`
	SellerSwiftCode            string    `json:"seller_swiftcode"`
	NewBank                    string    `json:"newbank"`
	BankAccNo                  string    `json:"bankaccno"`
	SellerBankAccNo            string    `json:"sellerbank_accno"`
	PinCode                    string    `json:"pincode"`
	AccNo                      string    `json:"acc_no"`
	OptionASwiftCode           string    `json:"optionA_swiftcode"`
	OptionDBankName            string    `json:"optionD_bankname"`
	OptionDBankAddress         []string  `json:"optionD_bankaddr"`
	SalesPurchaseForm          string    `json:"salespurchase_formcdn"`
	SellerName                 string    `json:"seller_name"`
	SellerCompanyName          string    `json:"seller_companyname"`
	SellerEmail                string    `json:"seller_mail"`
	SellerMobile               string    `json:"seller_mobile"`
	SellerAddress              []string  `json:"seller_address"`
	SellerContactPerson        string    `json:"seller_contactperson"`
	SellerFaxNo                string    `json:"seller_faxno"`
	BuyerAddress               []string  `json:"buyer_address"`
	OrderStatus                string    `json:"order_status"`
	Address                    string    `json:"address"`
	Contact                    string    `json:"contact_person"`
	TelNo                      string    `json:"Phone"`
	FaxNo                      string    `json:"fax_no"`
	BeneficiaryName            string    `json:"beneficiary_name"`
	BeneficiaryAddress         string    `json:"beneficiary_address"`
	PreferredBankName          string    `json:"preferred_bankname"`
	PreferredBankAddr          string    `json:"preferred_bankaddr"`
	BuyerBankMail              string    `json:"buyer_bankmail"`
	SellerPreferBankName       string    `json:"sellerprefer_bankname"`
	SellerPreferBankAddr       []string  `json:"sellerprefer_bankaddr"`
	SellerBankMail             string    `json:"seller_bankmail"`
	LcIssuanceMode             string    `json:"lc_issuance_mode"`
	ModeOfLCIssuance           []string  `json:"modeoflc_issuance"`
	CurrencyAmount             []string  `json:"currency_amount"`
	CurrencyType               string    `json:"currency_type"`
	Tolerance                  string    `json:"tolerance"`
	Expiry                     string    `json:"expiry"`
	LcTenor                    string    `json:"lctenor"`
	LcTenorDiscountCharges     string    `json:"lc_tenor_discount_charges"`
	SpecifyTax                 string    `json:"specify_tax"`
	LcIssuanceModeOthers       []string  `json:"lcissuance_modeothers"`
	FullSetCleanBillOthers     []string  `json:"fullset_cleanbillothers"`
	AirwayBillOthers           []string  `json:"airway_billothers"`
	GoodsDescriptionOthers     []string  `json:"goods_description_others"`
	TTDescription              []string  `json:"tt_description"`
	DADescription              []string  `json:"DA_description"`
	SpecifyTenor               string    `json:"specify_tenor"`
	SpecifyTenorValue          string    `json:"specify_tenorvalue"`
	TenorOtherTerms            string    `json:"tenor_otherterms"`
	TenorOtherTermsValue       []string  `json:"tenor_othertermsvalue"`
	Bill                       []string  `json:"bill"`
	DeliveryOrderInfo          []string  `json:"delivery_orderinfo"`
	Documents                  []string  `json:"documents"`
	OtherDocs                  []string  `json:"other_docs"`
	PlaceOfReceipt             string    `json:"placeof_receipt"`
	PortOfLoading              string    `json:"portof_loading"`
	PortOfDischarge            string    `json:"portof_discharge"`
	DocumentsPresented         string    `json:"documents_presented"`
	LatestShipDate             string    `json:"latest_shipdate"`
	PartialShipment            string    `json:"partial_shipment"`
	TransShipment              string    `json:"trans_shipment"`
	InstructionInsurance       string    `json:"insurance_instruction"`
	FullSetInsurance           string    `json:"fullset_insurance"`
	InsuranceCoverByShipper    string    `json:"insurancecover_byshipper"`
	OtherTerms                 []string  `json:"other_terms"`
	GoodsDescription           string    `json:"goods_description"`
	OtherCharges               []string  `json:"other_charges"`
	ShipmentFrom               string    `json:"shipment_from"`
	ShipmentTo                 string    `json:"shipment_to"`
	ShipmentDate               string    `json:"shipment_date"`
	DeliveryTerms              string    `json:"delivery_terms"`
	PackagingTerms             string    `json:"packaging_terms"`
	QuotePrice                 string    `json:"quote_price"`
	QuoteValidity              string    `json:"quote_validity"`
	SubTotalAmount             string    `json:"subtotal_amount"`
	InsuranceByShipperOthers   []string  `json:"insuranceby_shipperothers"`
	Freight                    string    `json:"freight"`
	TotalCNFAmount             string    `json:"totalcnf_amount"`
	Insurance                  string    `json:"insurance"`
	TotalCIFAmount             string    `json:"totalcif_amount"`
	Shipments                  []string  `json:"shipment"`
	ShippingTerms              []string  `json:"shipping_terms"`
	OtherTermsBySeller         []string  `json:"otherterms_byseller"`
	OtherTermsByBuyer          []string  `json:"otherterms_bybuyer"`
	PaymentTerms               []string  `json:"payment_terms"`
	SellerTerms                []string  `json:"seller_terms"`
	LCPresentationLocation     string    `json:"lcpresentation_location"`
	PresentationPeriod         string    `json:"period_presentation"`
	ChatStatus                 string    `json:"chat_status"`
	SellerInput                string    `json:"seller_input"`
	BuyerInput                 string    `json:"buyer_input"`
	AmendmentForm              []string  `json:"conversation"`
	AmendmentTime              string    `json:"time"`
	Usertype                   string    `json:"usertype"`
	PaymentTermsComments       []string  `json:"paymentterms_comments"`
	OtherBillOthers            []string  `json:"otherbill_others"`
	Position                   []string  `json:"position"`
	RmPosition                 []int     `json:"rm_position"`
	NotInPlatformBuyer         string    `json:"notinplatform_buyer"`
	NotInPlatformSeller        string    `json:"notinplatform_seller"`
	NotInPlatformBuyerBank     string    `json:"notinplatform_buyerbank"`
	NotInPlatformSellerBank    string    `json:"notinplatform_sellerbank"`
	CreditDays                 string    `json:"credit_days"`
	CreditTerms                string    `json:"credit_terms"`
	CreditOthers               []string  `json:"credit_others"`
	SellerRegisteredIn         string    `json:"seller_registeredin"`
	SellerWebsiteAddress       string    `json:"seller_websiteaddress"`
	SellerState                string    `json:"seller_state"`
	SellerCity                 string    `json:"seller-city"`
	SellerPinCode              string    `json:"seller-pincode"`
	CountryOfOrigin            string    `json:"country_oforigin"`
	CountryOfSupply            string    `json:"country_ofsupply"`
	BuyerRegisteredNo          string    `json:"buyer_registredno"`
	TaxType                    string    `json:"tax_type"`
	TaxNumber                  string    `json:"tax-number"`
	BuyerCountry               string    `json:"buyer_country"`
	BuyerState                 string    `json:"buyer_state"`
	BuyerCity                  string    `json:"buyer_city"`
	BuyerPinCode               string    `json:"buyer_pincode"`
	Description                []string  `json:"description"`
	TaxEnable                  string    `json:"tax_enable"`
	Discount                   string    `json:"discount"`
	DiscountIn                 string    `json:"discount_in"`
	FlatAmount                 string    `json:"flat_amount"`
	InvoiceValueOtherCharges   string    `json:"invoicevalue_othercharges"`
	InvoiceOrderTaxID          []string  `json:"invoiceorder_taxid"`
	InvoiceOrderTaxName        []string  `json:"invoiceorder_taxname"`
	InvoiceOrderTaxValue       []string  `json:"invoiceorder_taxvalue"`
	InvoiceOrderChargesID      []string  `json:"invoiceorder_chargesid"`
	InvoiceOrderChargesName    []string  `json:"invoiceorder_chargesname"`
	InvoiceOrderChargesValue   []string  `json:"invoiceorder_chargesvalue"`
	InvoiceOrderDiscount       []string  `json:"invoiceorder_discount"`
	SellerCountry              string    `json:"seller_country"`
	RecordOrderType            string    `json:"record_ordertype"`
	InvoiceType                string    `json:"invoice_type"`
	RecordType                 string    `json:"record_type"`
	InvoiceSaveAsDraft         string    `json:"invoice_saveasdraft"`
	InvoiceDocumentNumber      string    `json:"document_no"`
	DiscountPer                string    `json:"discount_per"`
	ShipState                  string    `json:"ship_state"`
	ShipCountry                string    `json:"ship_country"`
	ShipPinCode                string    `json:"ship_pincode"`
	ShipCity                   string    `json:"ship_city"`
	BlNo                       string    `json:"bl_no"`
	BlDate                     string    `json:"bl_date"`
	VesselName                 string    `json:"vessel_name"`
	InvoiceNo                  string    `json:"invoice_no"`
	InvoiceDate                string    `json:"invoice_date"`
	OrderTitle                 string    `json:"order_title"`
	TotalIncoTerms             string    `json:"total_incoterms"`
	InstallmentID              []string  `json:"installment_id"`
	InstallmentNo              []string  `json:"installment_no"`
	InstallmentDate            []string  `json:"installment_date"`
	InstallmentAmount          []string  `json:"installment_amount"`
	InstallmentIn              string    `json:"installment_in"`
	InstallmentInterval        string    `json:"installment_interval"`
	CreditDaysLimit            string    `json:"creditdays_limit"`
	CreditDate                 string    `json:"credit_date"`
	InvoiceStatus              string    `json:"invoice_status"`
	InvoiceAmendmentForm       []string  `json:"invoice_conversation"`
	BaseOrderID                string    `json:"baseorder_id"`
	OtherPaymentTerms          string    `json:"otherpayment_terms"`
	TenorType                  string    `json:"tenor_value"`
	OtherTenorTypeValue        string    `json:"othertenor_value"`
	DueDate                    string    `json:"due_date"`
	LcValue                    string    `json:"lc_value"`
	SellerApprovedDate         string    `json:"seller_approveddate"`
	BuyerApprovedDate          string    `json:"buyer_approveddate"`
	OrderSubmissionDate        string    `json:"order_submissiondate"`
	OrderApprovalDate          string    `json:"order_approvaldate"`
	ContainerNo                []string  `json:"container_no"`
	SealNo                     []string  `json:"seal_no"`
	DeliveryNoteType           []string  `json:"delivery_notetype"`
	ShippingMarks              []string  `json:"shipping_marks"`
	NetWeight                  []string  `json:"net_weight"`
	NetWeightuom               []string  `json:"netweightuom"`
	GrossWeight                []string  `json:"gross_weight"`
	GrossWeightuom             []string  `json:"grossweightuom"`
	NoOfPackages               []string  `json:"noof_packages"`
	Feedback                   []string  `json:"feedback"`
	DeliveryPosition           []string  `json:"delivery_position"`
	PaymentTermsOthers         []string  `json:"paymentterms_others"`
	RequestStatus              string    `json:"request_status"`
	CreatedAt                  time.Time `json:"created_at"`
	UpdatedAt                  time.Time `json:"updated_at"`
	NotinPlatform              string    `json:"notin_platform"`
	NotinPlatformFName         string    `json:"notinplatform_fname"`
	NotinPlatformLName         string    `json:"notinplatform_lname"`
	NotinPlatformFaxNO         string    `json:"notinplatform_Faxno"`
	NotinPlatformAddress       string    `json:"notinplatform_address"`
	NotinPlatformContactPerson string    `json:"notinplatform_contactperson"`
	NotinPlatformEmail         string    `json:"notinplatform_email"`
	NotinPlatformUserType      string    `json:"notinplatform_usertype"`
	NotinPlatformMobile        string    `json:"notinplatform_mobile"`
	NotinPlatformCompanyName   string    `json:"notinplatformc_ompanyname"`
	DocCredit                  string    `json:"doc_credit"`
}
